### ISSUE TITLE
FEATURE : Design for Profile Section 

### ISSUE THREAD

**Issue by bottercode** [bottercode/DevGram#39]
Design a profile page for the users.
Submit your ideas below by putting up a screenshot.

**Comment by minnayu** [comment]
Hello, I would like to work on this issue!

**Comment by skgx** [comment]
@minnayu Sure you can start by providing us a design first.

**Comment by minnayu** [comment]
@skgx @bottercode This is the design I came up with, this is from the perspective of viewing someone else's profile. Their information is displayed on the left, their projects are listed in the middle, and their recent activity on the platform is displayed on the right.

<img width="822" alt="Screen Shot 2023-04-25 at 11 29 48 PM" src="https://user-images.githubusercontent.com/69655024/234488504-fc084018-ea08-42fc-a293-2c871bd3196b.png">

**Comment by skgx** [comment]
@minnayu you can proceed with the code.
But make sure to follow the guidelines in the readme file.

**Comment by minnayu** [comment]
@skgx Thank you for accepting my idea. However, I don't think I will be able to complete the code in a timely manner due to being a full-time university student with finals and the end of the semester coming soon. I was just hoping to provide a front-end mockup as a rough idea of what the profile page would look like. I think it would be best if the code was assigned to someone else, thank you!
